apiVersion: v1
kind: Service
metadata:
  name: nginx-k8s-task-nodeport-service
  labels:
    app: k8s-task
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
  selector:
    app: k8s-task
