apiVersion: v1
kind: Service
metadata:
  name: nginx-k8s-task-clusterip-service
  labels:
    app: k8s-task
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: k8s-task
